// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdaniEP02RbMQlckDzCA6PWuSwz4dSXu4',
    appId: '1:327500572326:web:b006044726a8a92affb667',
    messagingSenderId: '327500572326',
    projectId: 'carseva-eb8af',
    authDomain: 'carseva-eb8af.firebaseapp.com',
    storageBucket: 'carseva-eb8af.firebasestorage.app',
    measurementId: 'G-6476D32JH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1SAEUzLz5qYLjQtHAdNub43ijBJzqKiw',
    appId: '1:327500572326:android:436987bcac8ea012ffb667',
    messagingSenderId: '327500572326',
    projectId: 'carseva-eb8af',
    storageBucket: 'carseva-eb8af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX3hacepz95bJwc2F56iPNtNXBSrLeUoo',
    appId: '1:327500572326:ios:a3e9dd45765b866affb667',
    messagingSenderId: '327500572326',
    projectId: 'carseva-eb8af',
    storageBucket: 'carseva-eb8af.firebasestorage.app',
    iosClientId: '327500572326-7m5048mo8g0qqc4a6hj7sic97dim4lu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.carseva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX3hacepz95bJwc2F56iPNtNXBSrLeUoo',
    appId: '1:327500572326:ios:a3e9dd45765b866affb667',
    messagingSenderId: '327500572326',
    projectId: 'carseva-eb8af',
    storageBucket: 'carseva-eb8af.firebasestorage.app',
    iosClientId: '327500572326-7m5048mo8g0qqc4a6hj7sic97dim4lu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.carseva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdaniEP02RbMQlckDzCA6PWuSwz4dSXu4',
    appId: '1:327500572326:web:68504644f7aeca45ffb667',
    messagingSenderId: '327500572326',
    projectId: 'carseva-eb8af',
    authDomain: 'carseva-eb8af.firebaseapp.com',
    storageBucket: 'carseva-eb8af.firebasestorage.app',
    measurementId: 'G-XPM9MNWK84',
  );
}
