// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5WkWFvvMnqusM3JT04KNvaR0OYFSmiv4',
    appId: '1:280136763210:web:437d55c6d20b680e72a3b3',
    messagingSenderId: '280136763210',
    projectId: 'carseva-f5a6e',
    authDomain: 'carseva-f5a6e.firebaseapp.com',
    databaseURL: 'https://carseva-f5a6e-default-rtdb.firebaseio.com',
    storageBucket: 'carseva-f5a6e.firebasestorage.app',
    measurementId: 'G-BX3LG8RFDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7UTurVWRYxWllI6w5oXeJ4zF8AxtXraA',
    appId: '1:280136763210:android:0c2524782c674eda72a3b3',
    messagingSenderId: '280136763210',
    projectId: 'carseva-f5a6e',
    databaseURL: 'https://carseva-f5a6e-default-rtdb.firebaseio.com',
    storageBucket: 'carseva-f5a6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABYbI_BZ-vh9eXB8k5bCFZyaL_dejaM7k',
    appId: '1:280136763210:ios:a69e5e878e1d8cc472a3b3',
    messagingSenderId: '280136763210',
    projectId: 'carseva-f5a6e',
    databaseURL: 'https://carseva-f5a6e-default-rtdb.firebaseio.com',
    storageBucket: 'carseva-f5a6e.firebasestorage.app',
    androidClientId: '280136763210-qmlt777lr6iatb37s5d5ic7jeptpiu41.apps.googleusercontent.com',
    iosClientId: '280136763210-g4h0i0st4q59jvbk9l80b2a9gr9duov3.apps.googleusercontent.com',
    iosBundleId: 'com.example.carseva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABYbI_BZ-vh9eXB8k5bCFZyaL_dejaM7k',
    appId: '1:280136763210:ios:a69e5e878e1d8cc472a3b3',
    messagingSenderId: '280136763210',
    projectId: 'carseva-f5a6e',
    databaseURL: 'https://carseva-f5a6e-default-rtdb.firebaseio.com',
    storageBucket: 'carseva-f5a6e.firebasestorage.app',
    androidClientId: '280136763210-qmlt777lr6iatb37s5d5ic7jeptpiu41.apps.googleusercontent.com',
    iosClientId: '280136763210-g4h0i0st4q59jvbk9l80b2a9gr9duov3.apps.googleusercontent.com',
    iosBundleId: 'com.example.carseva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5WkWFvvMnqusM3JT04KNvaR0OYFSmiv4',
    appId: '1:280136763210:web:b7f7927cadd7f58472a3b3',
    messagingSenderId: '280136763210',
    projectId: 'carseva-f5a6e',
    authDomain: 'carseva-f5a6e.firebaseapp.com',
    databaseURL: 'https://carseva-f5a6e-default-rtdb.firebaseio.com',
    storageBucket: 'carseva-f5a6e.firebasestorage.app',
    measurementId: 'G-M0W3CK5ZBW',
  );

}